def build(context):
    context.install_files(
        "${PYTHONDIR}/borg_explorer/templates",
        [
            "index.html",
            "borgview.css",
            "borgview.js",
            "analytics.js",
            ]
        )

    context.recurse("core")
    context.recurse("views")

