def build(context):
    context.install_files(
        "${PYTHONDIR}/borg_explorer/templates/views",
        [
            "cluster.js",
            "table.js",
            "vector.js"
            ]
        )

    context.recurse("cluster")

