def build(context):
    context(
        source = [
            "__init__.py",
            ],
        install_path = "${PYTHONDIR}/borg_explorer",
        )

    context.recurse("templates")
    context.recurse("tools")

